### ISSUE TITLE
Add Windows support for experiment setup

### ISSUE THREAD

**Issue by Jakob-Bach** [mathefuchs/al-for-sat-solver-benchmarking#3]
The steps described in README to address issue #2 are partly Linux-specific (shell script, some of the packages in the `conda` environment).

**Comment by mathefuchs** [comment]
Done and tested on Windows (cf. the [run script](https://github.com/mathefuchs/al-for-sat-solver-benchmarking/blob/main/run_debug.ps1) and the updated [requirements file](https://github.com/mathefuchs/al-for-sat-solver-benchmarking/blob/main/requirements.txt))
